<?php
/**
 * Minimum Order Fee extension
 *
 * NOTICE OF LICENSE
 *
 * This extension is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This extension is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this file.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    UnleashedTech_MinOrderFee
 * @package     UnleashedTech_MinOrderFee
 * @copyright   Copyright (c) 2014 Unleashed Technologies, LLC. (http://www.unleashed-technologies.com)
 * @license     https://www.gnu.org/licenses/gpl-3.0.txt
 */
?>
<?php $_source = $this->getSource() ?>
<?php if ($_source): ?>
    <tr>
        <td class="label"><?php echo $this->getShippingLabel() ?></td>
        <td><input type="text" name="creditmemo[shipping_amount]"
                   value="<?php echo $this->getShippingAmount() ?>"
                   class="input-text not-negative-amount"
                   style="width:60px;text-align:right" id="shipping_amount"/>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <div id="shipping_amount_adv"></div>
        </td>
    </tr>
    <tr>
        <td class="label"><?php echo $this->getMinOrderFeeLabel() ?></td>
        <td><input type="text" name="creditmemo[min_order_fee]"
                   value="<?php echo $this->getMinOrderFeeAmount() ?>"
                   class="input-text not-negative-amount"
                   style="width:60px;text-align:right" id="min_order_fee"/></td>
    </tr>
    <tr>
        <td colspan="2">
            <div id="min_order_fee_adv"></div>
        </td>
    </tr>
    <tr>
        <td class="label"><?php echo $this->helper('sales')->__('Adjustment Refund') ?></td>
        <td><input type="text" name="creditmemo[adjustment_positive]"
                   value="<?php echo $_source->getBaseAdjustmentFeePositive()
                       * 1 ?>" class="input-text not-negative-amount"
                   style="width:60px;text-align:right"
                   id="adjustment_positive"/></td>
    </tr>
    <tr>
        <td colspan="2">
            <div id="adjustment_positive_adv"></div>
        </td>
    </tr>
    <tr>
        <td class="label"><?php echo $this->helper('sales')->__('Adjustment Fee') ?></td>
        <td><input type="text" name="creditmemo[adjustment_negative]"
                   value="<?php echo $_source->getBaseAdjustmentFeeNegative() * 1 ?>"
                   class="input-text not-negative-amount"
                   style="width:60px;text-align:right"
                   id="adjustment_negative"/></td>
    </tr>
    <tr>
        <td colspan="2">
            <div id="adjustment_negative_adv"></div>
        </td>
    </tr>
    <script type="text/javascript">
        //<![CDATA[
        Validation.addAllThese([
            ['not-negative-amount', '<?php echo $this->helper('sales')->__('Please enter positive number in this field.') ?>', function (v) {
                if (v.length)
                    return /^\s*\d+([,.]\d+)*\s*%?\s*$/.test(v);
                else
                    return true;
            }]
        ]);

        if ($('shipping_amount')) {
            $('shipping_amount').advaiceContainer = $('shipping_amount_adv');
            unblockSubmit('shipping_amount');
        }
        if ($('min_order_fee')) {
            $('min_order_fee').advaiceContainer = $('min_order_fee_adv');
            unblockSubmit('min_order_fee');
        }
        if ($('adjustment_positive')) {
            $('adjustment_positive').advaiceContainer = $('adjustment_positive_adv');
            unblockSubmit('adjustment_positive');
        }
        if ($('adjustment_negative')) {
            $('adjustment_negative').advaiceContainer = $('adjustment_negative_adv');
            unblockSubmit('adjustment_negative');
        }

        function unblockSubmit(id) {
            $(id).observe('focus', function (event) {
                if ($$('button[class="scalable update-button disabled"]').size() > 0) {
                    enableElements('submit-button');
                }
            });
        }
        //]]>
    </script>
<?php endif; ?>
